services:
  db:
    image: postgres:14
    container_name: postgres
    volumes:
      - todo-db-store:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'root'

  app:
    build:
      context: ./app/gin/
    working_dir: /go/src/app
    tty: true
    volumes:
      - ./app:/go/src/app
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_NAME: postgres
    ports:
      - "8081:8081"
    depends_on:
      - db

  node:
    build:
      context: ./app/gin/view/
    working_dir: /go/src/app/gin/view
    tty: true
    ports: 
      - 5173:5173
    volumes:
      - ./app/gin/view:/go/src/app/gin/view
    environment:
      - NODE_ENV=development
    command: sh -c "npm install && npm run dev"
    depends_on:
      - app
    

volumes:
  todo-db-store: {}